<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0;net9.0-android;net9.0-ios</TargetFrameworks>		
		<UseMaui>true</UseMaui>
		<MauiVersion>9.0.40</MauiVersion>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>

		<RootNamespace>AiForms.Dialogs</RootNamespace>

		<PackageId>AiForms.Maui.Dialogs</PackageId>
		<Authors>kamu</Authors>
		<Company>kamu</Company>
		<Product>AiForms.Dialogs for .NET MAUI</Product>
		<PackageProjectUrl>https://github.com/muak/AiForms.Maui.Dialogs</PackageProjectUrl>
		<PackageLicenseUrl>https://github.com/muak/AiForms.Maui.Dialogs/blob/master/LICENSE.txt</PackageLicenseUrl>
		<PackageIconUrl>https://raw.githubusercontent.com/muak/AiForms.Dialogs/master/images/icon.png</PackageIconUrl>
		<Description>This is a collection of Custom Dialogs (Loading, Toast, CustomDialog) that can be defined with XAML for .NET MAUI (Android / iOS). This allows you to freely design the dialog content and arrange anywhere without custom renderer and effects.</Description>
		<PackageReleaseNotes>
			.NET9 supported
        </PackageReleaseNotes>
		<PackageTags>MAUI dialog toast loading progress popup xaml netstandard ios android</PackageTags>

		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <EnableCodeSigning>False</EnableCodeSigning>
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
	  <DebugSymbols>true</DebugSymbols>
	  <WarningLevel>4</WarningLevel>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<!-- Android -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net9.0-android')) != true">
		<Compile Remove="**\**\*.Android.cs" />
		<None Include="**\**\*.Android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
		<Compile Remove="**\Android\**\*.cs" />
		<None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />		
	</ItemGroup>

	<!-- iOS -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net9.0-ios')) != true">
		<Compile Remove="**\**\*.iOS.cs" />
		<None Include="**\**\*.iOS.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
		<Compile Remove="**\iOS\**\*.cs" />
		<None Include="**\iOS\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- NET -->
	<ItemGroup Condition="'$(TargetFramework)' != 'net9.0'">
		<Compile Remove="**\**\*.Net.cs" />
		<None Include="**\**\*.Net.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Extensions\" />
	  <None Remove="Platforms\Android\Extensions\" />
	  <None Remove="Platforms\Android\Resources\layout\loading_dialog_layout.axml" />
	  <None Remove="Platforms\Android\Resources\anim\extra_dialog_exit.xml" />
	  <None Remove="Platforms\Android\Resources\anim\extra_dialog_enter.xml" />
	  <None Remove="Platforms\Android\Resources\values\Strings.xml" />
	  <None Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Extensions\" />
	  <Folder Include="Platforms\iOS\" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="Loading\LoadingBase.iOS.cs" />
	</ItemGroup>
	<ItemGroup>
	  <AndroidResource Include="Platforms\Android\Resources\layout\loading_dialog_layout.axml" />
	  <AndroidResource Include="Platforms\Android\Resources\anim\extra_dialog_exit.xml" />
	  <AndroidResource Include="Platforms\Android\Resources\anim\extra_dialog_enter.xml" />
	  <AndroidResource Include="Platforms\Android\Resources\values\Strings.xml" />
	  <AndroidResource Include="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	</ItemGroup>
</Project>
